### ISSUE TITLE
setup endpoint response should refer to self, not controller

### ISSUE THREAD

**Issue by HomeACcessoryKid** [maximkulkin/esp32-homekit-camera#6]
in my opinion on reading the apple specs, the response of setup endpoints need to refer to the camera, not the controller.
This means that e.g. this line in app_main near line 268 is wrong and all that stems from it
```
    tlv_add_tlv_value(response, 3, controller_address);
```

**Comment by maximkulkin** [comment]
Somewhat it does, although controller should already know IP address of camera - it's IP address of accessory. Since video streaming is a PUSH, not PULL (camera need to send RTP packets to controller, not the controller establishing connection to camera), I guess, controller doesn't really check/care where packets come from, given they use proper encryption key.Specs sometimes are vague or even wrong. I based this mainly on observing how other implementations do that.
